import { contextBridge, ipcRenderer } from "electron";
import type {
  ApprovalDecisionInput,
  DesktopEvent,
  PrivoraDesktopApi,
  SaveSettingsInput,
  SaveThreadSettingsInput,
  StartTurnInput,
  PrepareTurnUndoInput,
  UndoTurnChangesInput,
  RequestUserInputResponseInput,
  PrivoraAuthInput,
  BrowserBoundsInput,
  BrowserDownloadInput,
  BrowserShieldsInput,
  BrowserFormAnalyzeInput,
  BrowserFormFillInput,
  BrowserFormSubmitInput,
  BrowserFormValidateInput,
  BrowserInspectInput,
  BrowserNavigationInput,
  BrowserOpenInput,
  BrowserOverlayInput,
  BrowserTabInput,
  BrowserToolsMenuInput,
  BrowserViewportInput,
  BrowserDiagnoseInput,
  BrowserEvidenceVaultInput,
  BrowserWorkflowAssertInput,
  BrowserWorkflowInput,
  ImportAttachmentInput,
  NotesCloseTabInput,
  NotesCreateInput,
  NotesDeleteInput,
  NotesListInput,
  NotesOpenFileInput,
  NotesOpenInput,
  NotesRenameInput,
  NotesSaveInput,
  NotesUpdateInput,
  StorageCleanupInput,
} from "../shared/types";
import { channels } from "../main/ipc/channels";

const api: PrivoraDesktopApi = {
  debugEnabled: typeof process !== "undefined" && process.env.PRIVORA_DEBUG === "1",
  getSnapshot: () => ipcRenderer.invoke(channels.getSnapshot),
  getThreadHistoryPage: (input) => ipcRenderer.invoke(channels.getThreadHistoryPage, input),
  getMessageDetail: (messageId) => ipcRenderer.invoke(channels.getMessageDetail, messageId),
  getToolEventDetail: (toolId) => ipcRenderer.invoke(channels.getToolEventDetail, toolId),
  importAttachment: (input: ImportAttachmentInput) => ipcRenderer.invoke(channels.importAttachment, input),
  createThread: (workspaceId?: string | null) => ipcRenderer.invoke(channels.createThread, workspaceId),
  renameThread: (threadId: string, title: string) => ipcRenderer.invoke(channels.renameThread, threadId, title),
  toggleThreadStar: (threadId: string) => ipcRenderer.invoke(channels.toggleThreadStar, threadId),
  deleteThread: (threadId: string) => ipcRenderer.invoke(channels.deleteThread, threadId),
  selectWorkspace: () => ipcRenderer.invoke(channels.selectWorkspace),
  removeWorkspace: (workspaceId: string) => ipcRenderer.invoke(channels.removeWorkspace, workspaceId),
  setActiveThread: (threadId: string) => ipcRenderer.invoke(channels.setActiveThread, threadId),
  startTurn: (input: StartTurnInput) => ipcRenderer.invoke(channels.startTurn, input),
  continueRun: (threadId: string) => ipcRenderer.invoke(channels.continueRun, threadId),
  stopTurn: (threadId: string) => ipcRenderer.invoke(channels.stopTurn, threadId),
  answerRequestUserInput: (input: RequestUserInputResponseInput) => ipcRenderer.invoke(channels.answerRequestUserInput, input),
  decideApproval: (input: ApprovalDecisionInput) => ipcRenderer.invoke(channels.decideApproval, input),
  prepareTurnUndo: (input: PrepareTurnUndoInput) => ipcRenderer.invoke(channels.prepareTurnUndo, input),
  undoTurnChanges: (input: UndoTurnChangesInput) => ipcRenderer.invoke(channels.undoTurnChanges, input),
  searchContextMentions: (input) => ipcRenderer.invoke(channels.searchContextMentions, input),
  listWorkspaceDirectory: (input) => ipcRenderer.invoke(channels.listWorkspaceDirectory, input),
  readWorkspaceFile: (input) => ipcRenderer.invoke(channels.readWorkspaceFile, input),
  listNotes: (input: NotesListInput) => ipcRenderer.invoke(channels.listNotes, input),
  createNote: (input: NotesCreateInput) => ipcRenderer.invoke(channels.createNote, input),
  openNote: (input: NotesOpenInput) => ipcRenderer.invoke(channels.openNote, input),
  openNoteFile: (input: NotesOpenFileInput) => ipcRenderer.invoke(channels.openNoteFile, input),
  updateNote: (input: NotesUpdateInput) => ipcRenderer.invoke(channels.updateNote, input),
  saveNote: (input: NotesSaveInput) => ipcRenderer.invoke(channels.saveNote, input),
  saveNoteAs: (input: NotesSaveInput) => ipcRenderer.invoke(channels.saveNoteAs, input),
  renameNote: (input: NotesRenameInput) => ipcRenderer.invoke(channels.renameNote, input),
  deleteNote: (input: NotesDeleteInput) => ipcRenderer.invoke(channels.deleteNote, input),
  closeNoteTab: (input: NotesCloseTabInput) => ipcRenderer.invoke(channels.closeNoteTab, input),
  revealNote: (input: NotesOpenInput) => ipcRenderer.invoke(channels.revealNote, input),
  saveSettings: (input: SaveSettingsInput) => ipcRenderer.invoke(channels.saveSettings, input),
  saveThreadSettings: (input: SaveThreadSettingsInput) => ipcRenderer.invoke(channels.saveThreadSettings, input),
  startPrivoraBrowserAuth: () => ipcRenderer.invoke(channels.startPrivoraBrowserAuth),
  signInPrivora: (input: PrivoraAuthInput) => ipcRenderer.invoke(channels.signInPrivora, input),
  signUpPrivora: (input: PrivoraAuthInput) => ipcRenderer.invoke(channels.signUpPrivora, input),
  signOutPrivora: () => ipcRenderer.invoke(channels.signOutPrivora),
  refreshAiCredits: () => ipcRenderer.invoke(channels.refreshAiCredits),
  getBrowserState: (workspaceId: string) => ipcRenderer.invoke(channels.getBrowserState, workspaceId),
  setBrowserVisible: (workspaceId: string, visible: boolean) => ipcRenderer.invoke(channels.setBrowserVisible, workspaceId, visible),
  setBrowserBounds: (input: BrowserBoundsInput) => ipcRenderer.invoke(channels.setBrowserBounds, input),
  openBrowserUrl: (input: BrowserOpenInput) => ipcRenderer.invoke(channels.openBrowserUrl, input),
  navigateBrowser: (input: BrowserNavigationInput) => ipcRenderer.invoke(channels.navigateBrowser, input),
  setBrowserViewport: (input: BrowserViewportInput) => ipcRenderer.invoke(channels.setBrowserViewport, input),
  inspectBrowser: (input: BrowserInspectInput) => ipcRenderer.invoke(channels.inspectBrowser, input),
  browserTab: (input: BrowserTabInput) => ipcRenderer.invoke(channels.browserTab, input),
  browserDownload: (input: BrowserDownloadInput) => ipcRenderer.invoke(channels.browserDownload, input),
  browserShields: (input: BrowserShieldsInput) => ipcRenderer.invoke(channels.browserShields, input),
  browserFormAnalyze: (input: BrowserFormAnalyzeInput) => ipcRenderer.invoke(channels.browserFormAnalyze, input),
  browserFormFill: (input: BrowserFormFillInput) => ipcRenderer.invoke(channels.browserFormFill, input),
  browserFormValidate: (input: BrowserFormValidateInput) => ipcRenderer.invoke(channels.browserFormValidate, input),
  browserFormSubmit: (input: BrowserFormSubmitInput) => ipcRenderer.invoke(channels.browserFormSubmit, input),
  browserWorkflow: (input: BrowserWorkflowInput) => ipcRenderer.invoke(channels.browserWorkflow, input),
  browserAssert: (input: BrowserWorkflowAssertInput) => ipcRenderer.invoke(channels.browserAssert, input),
  browserEvidenceVault: (input: BrowserEvidenceVaultInput) => ipcRenderer.invoke(channels.browserEvidenceVault, input),
  browserDiagnose: (input: BrowserDiagnoseInput) => ipcRenderer.invoke(channels.browserDiagnose, input),
  browserEvidence: (workspaceId: string) => ipcRenderer.invoke(channels.browserEvidence, workspaceId),
  getStorageUsage: () => ipcRenderer.invoke(channels.getStorageUsage),
  cleanupStorage: (input: StorageCleanupInput) => ipcRenderer.invoke(channels.cleanupStorage, input),
  openBrowserDevTools: (workspaceId: string) => ipcRenderer.invoke(channels.openBrowserDevTools, workspaceId),
  showBrowserToolsMenu: (input: BrowserToolsMenuInput) => ipcRenderer.invoke(channels.showBrowserToolsMenu, input),
  showBrowserOverlay: (input: BrowserOverlayInput) => ipcRenderer.invoke(channels.showBrowserOverlay, input),
  openPath: (path: string) => ipcRenderer.invoke(channels.openPath, path),
  openExternalUrl: (url: string) => ipcRenderer.invoke(channels.openExternalUrl, url),
  listWorkspaceOpenTargets: () => ipcRenderer.invoke(channels.listWorkspaceOpenTargets),
  openWorkspaceTarget: (target) => ipcRenderer.invoke(channels.openWorkspaceTarget, target),
  getUpdateStatus: () => ipcRenderer.invoke(channels.getUpdateStatus),
  checkForUpdates: () => ipcRenderer.invoke(channels.checkForUpdates),
  installUpdate: () => ipcRenderer.invoke(channels.installUpdate),
  onUpdateStatusChanged: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, status: Awaited<ReturnType<PrivoraDesktopApi["getUpdateStatus"]>>) => callback(status);
    ipcRenderer.on(channels.updateStatusChanged, listener);
    return () => ipcRenderer.off(channels.updateStatusChanged, listener);
  },
  onZoomChanged: (callback: (percent: number) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, percent: number) => callback(percent);
    ipcRenderer.on(channels.zoomChanged, listener);
    return () => ipcRenderer.off(channels.zoomChanged, listener);
  },
  onEvent: (callback: (event: DesktopEvent) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: DesktopEvent) => callback(payload);
    ipcRenderer.on(channels.event, listener);
    return () => ipcRenderer.off(channels.event, listener);
  },
};

contextBridge.exposeInMainWorld("privoraDesktop", api);
