export const channels = {
  getSnapshot: "desktop:getSnapshot",
  createThread: "desktop:createThread",
  renameThread: "desktop:renameThread",
  toggleThreadStar: "desktop:toggleThreadStar",
  deleteThread: "desktop:deleteThread",
  setActiveThread: "desktop:setActiveThread",
  selectWorkspace: "desktop:selectWorkspace",
  startTurn: "desktop:startTurn",
  continueRun: "desktop:continueRun",
  stopTurn: "desktop:stopTurn",
  decideApproval: "desktop:decideApproval",
  searchContextMentions: "desktop:searchContextMentions",
  saveSettings: "desktop:saveSettings",
  openPath: "desktop:openPath",
  openWorkspaceTarget: "desktop:openWorkspaceTarget",
  event: "desktop:event",
} as const;
