export const channels = {
  getSnapshot: "desktop:getSnapshot",
  createThread: "desktop:createThread",
  renameThread: "desktop:renameThread",
  toggleThreadStar: "desktop:toggleThreadStar",
  deleteThread: "desktop:deleteThread",
  setActiveThread: "desktop:setActiveThread",
  selectWorkspace: "desktop:selectWorkspace",
  removeWorkspace: "desktop:removeWorkspace",
  startTurn: "desktop:startTurn",
  continueRun: "desktop:continueRun",
  stopTurn: "desktop:stopTurn",
  answerRequestUserInput: "desktop:answerRequestUserInput",
  decideApproval: "desktop:decideApproval",
  prepareTurnUndo: "desktop:prepareTurnUndo",
  undoTurnChanges: "desktop:undoTurnChanges",
  searchContextMentions: "desktop:searchContextMentions",
  listWorkspaceDirectory: "desktop:listWorkspaceDirectory",
  readWorkspaceFile: "desktop:readWorkspaceFile",
  saveSettings: "desktop:saveSettings",
  openPath: "desktop:openPath",
  openExternalUrl: "desktop:openExternalUrl",
  listWorkspaceOpenTargets: "desktop:listWorkspaceOpenTargets",
  openWorkspaceTarget: "desktop:openWorkspaceTarget",
  event: "desktop:event",
} as const;
