/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalRefundRouteImport } from './routes/legal/refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal/acceptable-use'
import { Route as DesktopConnectRouteImport } from './routes/desktop/connect'
import { Route as DesktopCallbackRouteImport } from './routes/desktop/callback'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthRecoveryRouteImport } from './routes/auth/recovery'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUsageRouteImport } from './routes/admin/usage'
import { Route as AccountUsageRouteImport } from './routes/account/usage'
import { Route as AccountBillingRouteImport } from './routes/account/billing'

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/legal/acceptable-use',
  path: '/legal/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopConnectRoute = DesktopConnectRouteImport.update({
  id: '/desktop/connect',
  path: '/desktop/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopCallbackRoute = DesktopCallbackRouteImport.update({
  id: '/desktop/callback',
  path: '/desktop/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoveryRoute = AuthRecoveryRouteImport.update({
  id: '/auth/recovery',
  path: '/auth/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountUsageRoute = AccountUsageRouteImport.update({
  id: '/account/usage',
  path: '/account/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBillingRoute = AccountBillingRouteImport.update({
  id: '/account/billing',
  path: '/account/billing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/usage': typeof AccountUsageRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/desktop/callback': typeof DesktopCallbackRoute
  '/desktop/connect': typeof DesktopConnectRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/usage': typeof AccountUsageRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/desktop/callback': typeof DesktopCallbackRoute
  '/desktop/connect': typeof DesktopConnectRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/usage': typeof AccountUsageRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/desktop/callback': typeof DesktopCallbackRoute
  '/desktop/connect': typeof DesktopConnectRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/pricing'
    | '/security'
    | '/account/billing'
    | '/account/usage'
    | '/admin/usage'
    | '/admin/users'
    | '/auth/recovery'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/desktop/callback'
    | '/desktop/connect'
    | '/legal/acceptable-use'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/account/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/pricing'
    | '/security'
    | '/account/billing'
    | '/account/usage'
    | '/admin/usage'
    | '/admin/users'
    | '/auth/recovery'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/desktop/callback'
    | '/desktop/connect'
    | '/legal/acceptable-use'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/account'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/download'
    | '/pricing'
    | '/security'
    | '/account/billing'
    | '/account/usage'
    | '/admin/usage'
    | '/admin/users'
    | '/auth/recovery'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/desktop/callback'
    | '/desktop/connect'
    | '/legal/acceptable-use'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/account/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRoute: typeof DownloadRoute
  PricingRoute: typeof PricingRoute
  SecurityRoute: typeof SecurityRoute
  AccountBillingRoute: typeof AccountBillingRoute
  AccountUsageRoute: typeof AccountUsageRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  DesktopCallbackRoute: typeof DesktopCallbackRoute
  DesktopConnectRoute: typeof DesktopConnectRoute
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop/connect': {
      id: '/desktop/connect'
      path: '/desktop/connect'
      fullPath: '/desktop/connect'
      preLoaderRoute: typeof DesktopConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop/callback': {
      id: '/desktop/callback'
      path: '/desktop/callback'
      fullPath: '/desktop/callback'
      preLoaderRoute: typeof DesktopCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/auth/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/usage': {
      id: '/account/usage'
      path: '/account/usage'
      fullPath: '/account/usage'
      preLoaderRoute: typeof AccountUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/billing': {
      id: '/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRoute: DownloadRoute,
  PricingRoute: PricingRoute,
  SecurityRoute: SecurityRoute,
  AccountBillingRoute: AccountBillingRoute,
  AccountUsageRoute: AccountUsageRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  DesktopCallbackRoute: DesktopCallbackRoute,
  DesktopConnectRoute: DesktopConnectRoute,
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
